# Generated by Django 4.2.30 on 2026-08-03 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('subject_template', models.CharField(max_length=500)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OutreachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('instagram', 'Instagram'), ('phone', 'Phone')], max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=320)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed'), ('replied', 'Replied')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebsiteInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_url', models.URLField(blank=True, max_length=1000)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('has_contact_page', models.BooleanField(default=False)),
                ('has_privacy_page', models.BooleanField(default=False)),
                ('has_https', models.BooleanField(default=False)),
                ('has_viewport_meta', models.BooleanField(default=False)),
                ('robots_allowed', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('-discovered_at',)},
        ),
        migrations.AlterModelOptions(
            name='lighthouseresult',
            options={'ordering': ('-checked_at',)},
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='website',
            new_name='website_url',
        ),
        migrations.RenameField(
            model_name='leadnote',
            old_name='body',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='lighthouseresult',
            old_name='accessibility_score',
            new_name='accessibility',
        ),
        migrations.RenameField(
            model_name='lighthouseresult',
            old_name='best_practices_score',
            new_name='best_practices',
        ),
        migrations.RenameField(
            model_name='lighthouseresult',
            old_name='performance_score',
            new_name='performance',
        ),
        migrations.RenameField(
            model_name='lighthouseresult',
            old_name='seo_score',
            new_name='seo',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='company_name',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='leadnote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lighthouseresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lighthouseresult',
            name='pwa_score',
        ),
        migrations.RemoveField(
            model_name='lighthouseresult',
            name='raw_result',
        ),
        migrations.RemoveField(
            model_name='lighthouseresult',
            name='url',
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='provider',
            field=models.CharField(choices=[('overpass', 'OpenStreetMap Overpass'), ('google_places', 'Google Places')], default='overpass', max_length=30),
        ),
        migrations.AddField(
            model_name='campaign',
            name='search_term',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_with_website',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_without_website',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='discovered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lead',
            name='do_not_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='lead',
            name='website_verification_status',
            field=models.CharField(choices=[('not_checked', 'Not checked'), ('confirmed_none', 'No website found in discovery source'), ('found_manually', 'Found manually'), ('social_only', 'Social only'), ('verified', 'Verified')], default='not_checked', max_length=30),
        ),
        migrations.AddField(
            model_name='lighthouseresult',
            name='checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lighthouseresult',
            name='cumulative_layout_shift',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lighthouseresult',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lighthouseresult',
            name='final_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='lighthouseresult',
            name='first_contentful_paint_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lighthouseresult',
            name='largest_contentful_paint_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lighthouseresult',
            name='strategy',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default='mobile', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lighthouseresult',
            name='total_blocking_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.campaign'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('ready', 'Ready'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('interested', 'Interested'), ('declined', 'Declined'), ('follow_up', 'Follow up'), ('do_not_contact', 'Do not contact'), ('invalid', 'Invalid')], default='new', max_length=30),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['discovered_at'], name='lead_discovered_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up_at'], name='lead_followup_idx'),
        ),
        migrations.AddIndex(
            model_name='lighthouseresult',
            index=models.Index(fields=['lead', 'strategy', '-checked_at'], name='lh_latest_idx'),
        ),
        migrations.AddField(
            model_name='websiteinspection',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_inspection', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_messages', to='leads.lead'),
        ),
    ]
