# Generated by Django 4.2.30 on 2026-08-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_emailtemplate_outreachmessage_websiteinspection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_name',
            field=models.CharField(max_length=255),
        ),
    ]
