# Generated by Django 4.2.30 on 2026-08-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='country',
            field=models.CharField(default='Greece', max_length=100),
        ),
    ]
