# Generated by Django 4.2.30 on 2026-08-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_campaign_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_places_enabled', models.BooleanField(default=False)),
                ('google_places_api_key', models.CharField(blank=True, max_length=500)),
                ('google_pagespeed_api_key', models.CharField(blank=True, max_length=500)),
                ('overpass_api_url', models.URLField(default='https://overpass-api.de/api/interpreter', max_length=500)),
                ('outbound_user_agent', models.CharField(default='LeadResearchDashboard/1.0 (personal research)', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'integration settings',
            },
        ),
    ]
