# Generated by Django 4.2.30 on 2026-08-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_integrationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='default_from_email',
            field=models.EmailField(default='webmaster@localhost', max_length=254),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_backend',
            field=models.CharField(choices=[('django.core.mail.backends.console.EmailBackend', 'Console (development)'), ('django.core.mail.backends.smtp.EmailBackend', 'SMTP')], default='django.core.mail.backends.console.EmailBackend', max_length=100),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
