# Generated by Django 4.2.30 on 2026-08-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_integrationsettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='text_search_query',
            field=models.CharField(blank=True, help_text='Optional Google Places free-text query, for example: Bar near Athens', max_length=300),
        ),
    ]
